apiVersion: v1
kind: Service
metadata:
  name: aim-engine-operator-controller-manager-metrics-service
  namespace: aim-engine-system
  labels:
    control-plane: controller-manager
spec:
  selector:
    control-plane: controller-manager
  ports:
  - name: https
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP 