apiVersion: aim.engine.amd.com/v1alpha1
kind: AIMCache
metadata:
  name: model-cache
  namespace: aim-engine
spec:
  storage:
    size: "100Gi"
    storageClass: "local-path"
    accessMode: "ReadWriteOnce"
  cleanup:
    schedule: "0 2 * * *"  # Daily at 2 AM
    maxAge: "7d"
    minFreeSpace: "20Gi"
  policies:
    maxModels: 10
    maxTotalSize: "80Gi"
    priorityModels:
    - "Qwen/Qwen2.5-7B-Instruct"
    - "Qwen/Qwen2.5-14B-Instruct"
  monitoring:
    enabled: true
    metrics:
    - "cache_hit_rate"
    - "cache_miss_rate"
    - "storage_utilization"
    - "model_access_count" 