apiVersion: aim.engine.amd.com/v1alpha1
kind: AIMEndpoint
metadata:
  name: qwen-7b-demo
  namespace: aim-engine
spec:
  model:
    id: "Qwen/Qwen2.5-7B-Instruct"
    version: "latest"
  recipe:
    autoSelect: true
    gpuCount: 1
  resources:
    gpuCount: 1
    cpu: "4"
    memory: "16Gi"
    memoryLimit: "32Gi"
    cpuLimit: "8"
  scaling:
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilization: 70
    targetMemoryUtilization: 80
  service:
    type: "NodePort"
    port: 8000
    targetPort: 8000
  cache:
    enabled: true
    storageClass: "local-path"
    size: "50Gi"
  monitoring:
    enabled: true
    prometheus:
      enabled: true
      interval: "30s"
      path: "/metrics"
  deployment:
    strategy:
      type: "RollingUpdate"
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
  image:
    repository: "localhost:5000/aim-vllm"
    tag: "latest"
    pullPolicy: "IfNotPresent" 