apiVersion: aim.engine.amd.com/v1alpha1
kind: AIMRecipe
metadata:
  name: qwen-7b-mi300x-bf16
  namespace: aim-engine
spec:
  modelId: "Qwen/Qwen2.5-7B-Instruct"
  hardware: "MI300X"
  precision: "bfloat16"
  backend: "vllm"
  description: "Qwen 7B model optimized for MI300X with bfloat16 precision"
  readinessLevel: "Production-Ready"
  
  configurations:
    - gpuCount: 1
      enabled: true
      args:
        - "--model"
        - "Qwen/Qwen2.5-7B-Instruct"
        - "--dtype"
        - "bfloat16"
        - "--max-model-len"
        - "16384"
        - "--gpu-memory-utilization"
        - "0.9"
        - "--trust-remote-code"
        - "true"
        - "--port"
        - "8000"
      env:
        VLLM_USE_ROCM: "1"
        HIP_VISIBLE_DEVICES: "0"
      resources:
        requests:
          amd.com/gpu: "1"
          memory: "16Gi"
          cpu: "4"
        limits:
          amd.com/gpu: "1"
          memory: "32Gi"
          cpu: "8"
      volumeMounts:
        - name: model-cache
          mountPath: "/workspace/model-cache"
          readOnly: false
    
    - gpuCount: 2
      enabled: true
      args:
        - "--model"
        - "Qwen/Qwen2.5-7B-Instruct"
        - "--dtype"
        - "bfloat16"
        - "--tensor-parallel-size"
        - "2"
        - "--max-model-len"
        - "16384"
        - "--gpu-memory-utilization"
        - "0.9"
        - "--trust-remote-code"
        - "true"
        - "--port"
        - "8000"
      env:
        VLLM_USE_ROCM: "1"
        HIP_VISIBLE_DEVICES: "0,1"
      resources:
        requests:
          amd.com/gpu: "2"
          memory: "32Gi"
          cpu: "8"
        limits:
          amd.com/gpu: "2"
          memory: "64Gi"
          cpu: "16"
      volumeMounts:
        - name: model-cache
          mountPath: "/workspace/model-cache"
          readOnly: false
  
  performance:
    expectedTokensPerSecond: 3000
    expectedLatencyMs: 50
    maxBatchSize: 16
    maxInputLength: 4096
    maxOutputLength: 2048
    gpuMemoryUtilization: 0.9
  
  tags:
    - "Chat"
    - "Instruction-Tuned"
    - "vLLM-Compatible"
    - "Lightweight"
  
  license: "Qwen License" 