apiVersion: aim.engine.amd.com/v1alpha1
kind: AIMRecipe
metadata:
  name: qwen-7b-recipe
  namespace: aim-engine
spec:
  model:
    id: "Qwen/Qwen2.5-7B-Instruct"
    version: "latest"
  precision: "bfloat16"
  backend: "vllm"
  configurations:
  - name: "single-gpu"
    gpuCount: 1
    enabled: true
    resources:
      cpu: "4"
      memory: "16Gi"
      gpu: "1"
    settings:
      tensorParallelSize: 1
      maxModelLen: 32768
      gpuMemoryUtilization: 0.9
  - name: "multi-gpu"
    gpuCount: 2
    enabled: true
    resources:
      cpu: "8"
      memory: "32Gi"
      gpu: "2"
    settings:
      tensorParallelSize: 2
      maxModelLen: 32768
      gpuMemoryUtilization: 0.9
  performance:
    latency:
      p50: 100
      p95: 200
      p99: 500
    throughput:
      requestsPerSecond: 10
      tokensPerSecond: 1000
  compatibility:
    frameworks:
    - "vllm"
    - "transformers"
    hardware:
    - "amd-gpu"
    - "rocm" 