# Basic monitoring setup for Minikube
# Note: This requires Prometheus Operator to be installed

---
# ServiceMonitor for AIM Engine metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aim-engine-recipe-monitor
  namespace: aim-engine-monitoring
  labels:
    app: aim-engine
    component: monitoring
    release: prometheus
spec:
  selector:
    matchLabels:
      app: aim-engine
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - aim-engine

---
# PrometheusRule for basic alerts
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: aim-engine-recipe-alerts
  namespace: aim-engine-monitoring
  labels:
    app: aim-engine
    component: monitoring
    release: prometheus
spec:
  groups:
  - name: aim-engine.rules
    rules:
    - alert: AIMEngineRecipeNotFound
      expr: aim_recipe_selection_total == 0
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "AIM Engine recipe not found"
        description: "No recipe has been selected for AIM Engine deployment"
    
    - alert: AIMEngineLowThroughput
      expr: aim_performance_tokens_per_second < 100
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "AIM Engine low throughput"
        description: "AIM Engine throughput is below expected levels"
    
    - alert: AIMEngineHighLatency
      expr: aim_gpu_memory_utilization > 0.95
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "AIM Engine high GPU utilization"
        description: "GPU memory utilization is very high"

---
# ConfigMap for basic Grafana dashboard
apiVersion: v1
kind: ConfigMap
metadata:
  name: aim-engine-minikube-dashboard
  namespace: aim-engine-monitoring
  labels:
    app: aim-engine
    component: dashboard
data:
  dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "title": "AIM Engine - Minikube Development",
        "tags": ["aim-engine", "minikube", "development"],
        "style": "dark",
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "Recipe Selection Overview",
            "type": "stat",
            "targets": [
              {
                "expr": "aim_recipe_selection_total",
                "legendFormat": "Recipe Selections"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "color": {
                  "mode": "palette-classic"
                },
                "custom": {
                  "displayMode": "list"
                }
              }
            },
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 0,
              "y": 0
            }
          },
          {
            "id": 2,
            "title": "Performance Metrics",
            "type": "timeseries",
            "targets": [
              {
                "expr": "aim_performance_tokens_per_second",
                "legendFormat": "Tokens/Second"
              },
              {
                "expr": "aim_gpu_memory_utilization",
                "legendFormat": "GPU Utilization"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 12,
              "y": 0
            }
          },
          {
            "id": 3,
            "title": "Request Count",
            "type": "stat",
            "targets": [
              {
                "expr": "aim_engine_requests_total",
                "legendFormat": "Total Requests"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 0,
              "y": 8
            }
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "refresh": "30s"
      }
    }

---
# Namespace for monitoring
apiVersion: v1
kind: Namespace
metadata:
  name: aim-engine-monitoring
  labels:
    name: aim-engine-monitoring 