apiVersion: v1
kind: Service
metadata:
  name: aim-engine-service
  namespace: aim-engine
  labels:
    app: aim-engine
spec:
  type: NodePort
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
    nodePort: 30080
  selector:
    app: aim-engine
  sessionAffinity: None
---
# ClusterIP service for internal access
apiVersion: v1
kind: Service
metadata:
  name: aim-engine-internal
  namespace: aim-engine
  labels:
    app: aim-engine
    type: internal
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: aim-engine
  sessionAffinity: None 