apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aim-engine-cache-pvc
  namespace: aim-engine
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Use default storage class in Minikube
  # storageClassName: manual 