apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aim-engine.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aim-engine.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path 