apiVersion: v1
kind: Service
metadata:
  name: {{ include "aim-engine.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aim-engine.labels" . | nindent 4 }}
    app.kubernetes.io/component: service
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "aim-engine.selectorLabels" . | nindent 4 }} 