apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: aim-engine-hpa
  namespace: aim-engine
  labels:
    app: aim-engine
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aim-engine
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 2
        periodSeconds: 15 