apiVersion: aim.engine.amd.com/v1alpha1
kind: AIMEndpoint
metadata:
  name: basic-aim-cpu
  namespace: aim-engine
spec:
  model:
    id: "Qwen/Qwen2.5-7B-Instruct"
    version: "latest"
  image:
    repository: "localhost:5000/aim-vllm"
    tag: "latest"
  recipe:
    autoSelect: true
    gpuCount: 0
  resources:
    cpu: "8"
    memory: "32Gi"
    gpuCount: 0
    cpuLimit: "16"
    memoryLimit: "64Gi"
  scaling:
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilization: 70
    targetMemoryUtilization: 80
  cache:
    enabled: false
  service:
    type: "NodePort"
    port: 8000
    targetPort: 8000
  deployment:
    strategy:
      type: "RollingUpdate"
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
  monitoring:
    enabled: false 